name: Deploy to Firebase on Merge
'on':
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies for Functions
        run: npm --prefix ./functions install
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --project medical-bot-project-3f141
        env:
          GCP_SA_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_MEDICAL_BOT_PROJECT_3F141 }}
